### ISSUE TITLE
Improve CSS Responsiveness

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/Weather-App-React#1]
### Description

Our project needs better responsiveness on various devices and screen sizes.

### Scope

- Update header navigation for smaller screens.
- Fit Background Properly in Website
- Implement media queries for breakpoints.

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- CSS
- Responsive Design
- Hacktoberfest

**Comment by Kiran-Alex** [comment]
Please Assign  This Issue To Me I would Like to Contribute to This issue

**Comment by imhardikdesai** [comment]
@Kiran-Alex , Sure Please start working on it

**Comment by imhardikdesai** [comment]
#2
